name: 'Application Update notification'

on:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches: [ master ]


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'setup-python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'install package'
        run: pip install requests
      - name: 'Get content'
        run: echo ${{ secrets.BIN_ID }} | python script.py
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        if: hashFiles('result*')
        with:
          server_address: smtp.126.com
          server_port: 25
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Chrome App (${{env.REPORT_DATE}})
          body: file://result.html
          to: yulong9@outlook.com
          from: GitHub Actions
          content_type: text/html
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run js
      run: node bookmarklet.js
